### ISSUE TITLE
Error Creating a Policy Rule to simply add a header

### ISSUE THREAD

**Issue by danterossi** [f5devcentral/terraform-provider-bigip-old#118]
I'm getting errors when trying to simply create a rule that adds a header to the request. The only examples I've found for terraform policy rules is to forward traffic to a pool.

Ex:

```resource "bigip_ltm_policy" "test-policy" {
  name = "test-policy"
  strategy = "all-match"
  requires = ["http"]
  published_copy = "Drafts/test-policy"
  controls = [""]
  rule  {
    name = "test-rule"
    action = {
      insert = true
      http_header = true
      key = "foo"
      value = "bar"
    }
  }
}

**Comment by danterossi** [comment]
Resulting error is:

`Error: Error applying plan:

1 error(s) occurred:

* bigip_ltm_policy.test-policy: 1 error(s) occurred:

* bigip_ltm_policy.test-policy: 0107186c:3: Policy '/Common/Drafts/test-policy', rule 'test-rule'; missing or invalid target.`

**Comment by dannyk81** [comment]
@danterossi this seems related to https://github.com/f5devcentral/terraform-provider-bigip/issues/112

The policy resource, unfortunately, seems broken in current state 😞 

@scshitole have you had any luck figuring out the root cause? looks like there are many configuration scenarios which fail for this resource.

**Comment by danterossi** [comment]
@dannyk81 thanks for the info

**Comment by adam-f5** [comment]
Repository Archived
